### ISSUE TITLE
common-js/ES6 import-export, webpack to output UMD builds

### ISSUE THREAD

**Issue by devdoomari** [asmcrypto/asmcrypto.js#112]
Hello!
I'm using webpack for my company's website build, and currently I have to build asmcrypto.js again for custom minimized version. 
Moreover, reading through the souce code takes long as I have to search for relevant function/variable names on the whole src directory.

What do you think about using common-js / es6 import/export statements
(with typescript)

I'll be working on this version, and I'd like to hear some opinions on this change.
ps: I'll do a quick pull-request for this soon : )

**Comment by alippai** [comment]
A part of this is done in 0.16.0. Open a new issue if you miss something, please.
