### ISSUE TITLE
Unit Test with Jest (node.js) and insecure origin warning.

### ISSUE THREAD

**Issue by nakwa** [asmcrypto/asmcrypto.js#128]
Hi,

I am looking for a way to disable the insecure origin warning when running my test suite (Jest on Node.js).

```
console.warn node_modules/asmcrypto.js/asmcrypto.js:5
      asmCrypto seems to be load from an insecure origin; this may cause to MitM-attack vulnerability. Consider using secure transport protocol.
```

In that case `global.location.protocol` is set to `about:`.
Any thoughts ? 

Thanks !

**Comment by alippai** [comment]
I'm not familiar with Jest. Can you help me why is the protocol set to `about:`?

**Comment by alippai** [comment]
Just removed the origin warning related code in 2.0
