### ISSUE TITLE
Module - Module

### ISSUE THREAD

**Issue by DesWurstes** [asmcrypto/asmcrypto.js#134]
I need sha256, but 130 KB is too much. Is it possible to create one file that has things which are only required for sha256?

**Comment by alippai** [comment]
You can include the module (src/hash/sha256/exports.js) directly, however that way the file is not minified, so you need post processing.

You can fork the lib and modify the contents of the src/entry-defaults.js file, install the required npm modules and run the `grunt` command.

**Comment by DesWurstes** [comment]
Thank you
