### ISSUE TITLE
Encrypt text longer than 16 bytes

### ISSUE THREAD

**Issue by jochenonline** [asmcrypto/asmcrypto.js#3]
When I do this:

```
asmCrypto.AES.encrypt( "This is a text with more than 16 characters!", '0123456789abcdef' );
```

I get:

```
RangeError: Source is too large
```

What is my fault?

**Comment by leoselig** [comment]
I'd add that this usually happens if you try to decrypt something that has not been encrypted before (because encryption adds a padding automatically)
