### ISSUE TITLE
"new asmCrypto.SHA256;" throws "is not a function" exception

### ISSUE THREAD

**Issue by ghost** [asmcrypto/asmcrypto.js#5]
The example code from the readme doesn't work (latest Chrome/Firefox). The following exception is thrown:
`TypeError: Property 'SHA256' of object #<Object> is not a function`

Maybe I am mistaken, but it looks like the constructor isn't exported at all. Is there a reason for that? I think `SHA256.process(chunk1).process(chunk2).finish().asHex()` would be great to use for more advanced use cases. For simpler cases with chunks, `SHA256.hex(arrayOfChunks)` could be sufficient too.

By the way, great project!

**Comment by rushglen** [comment]
just came across this same problem, could you explain how we can resolve this, there's nothing in the README ?
