### ISSUE TITLE
Document the release

### ISSUE THREAD

**Issue by alippai** [asmcrypto/asmcrypto.js#50]
On pull requests I'd like to be glad to provide the built asmcrypto.js however I don't know which flag should I use for it. Is it `grunt --with ALL` ? Can you add it to the README so others can help? :)

I know you don't like building everytime you commit, however I think you should tag the stable enough releases and beside this we should maintain a compiled/testpassinggreen devel version (on master branch).

**Comment by jdonaldson10** [comment]
Perhaps worth revisiting this post #119 and adding a [CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)?
