### ISSUE TITLE
Consider submitting this to CDNJS?

### ISSUE THREAD

**Issue by jvsteiner** [asmcrypto/asmcrypto.js#73]
Love the library - but I noticed it doesn't seem to be available via CDN anywhere...

**Comment by vibornoff** [comment]
There is one major issue. Library must be available **only from https-origin**.
Though it would be cool to submit this to CDNJS. I'll investigate deeply this issue in near future.
Thanks a lot for your feedback.

**Comment by mozfreddyb** [comment]
Your secure origin check seems to check the location of the document but not the location of the script, so I wonder if that makes your argument moot.
On a side note, if you want to ensure that the file loads from a CDN without manipulation, you could [use Subresource Integrity](https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/)
